name: Secrets workflow

env:
  DOTNET_VERSION: '8.0.x'
  API_CSPROJ_PATH: 'src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj'

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cron:
    name: Secrets demo
    runs-on: ubuntu-latest

    steps:
      - name: echo env variable
        run: echo "The env is ${{ env.API_CSPROJ_PATH }}"

      - name: echo secret variable
        run: echo "The secret is ${{ secrets.SECRET_API_KEY }}"
